type Query {
  users: [UserResponse!]!
  user(id: ID!): UserResponse
  imageMetadata(imageId: ID!): ImageMetadata
  posts: [PostResponse!]!
  post(id: ID!): PostResponse
}

type Mutation {
  createUser(input: CreateUserRequest!): UserResponse!
  updateUser(input: UpdateUserRequest!): UserResponse!
  deleteUser(id: ID!): Boolean!

  createImageUpload(input: CreateImageUploadInput!): CreateImageUploadResponse!
  deleteImage(imageId: ID!): Boolean!

  createPost(input: CreatePostRequest!): PostResponse!
  updatePost(input: UpdatePostRequest!): PostResponse!
  deletePost(id: ID!): Boolean!
}

type UserResponse {
  id: ID!
  name: String!
  profileImageId: ID
}

type ImageMetadata {
  imageId: ID!
  originalFileName: String!
  contentType: String!
  size: Int!
  downloadUrl: String!
}

type CreateImageUploadResponse {
  imageId: ID!
  uploadUrl: String!
}

type PostResponse {
  id: ID!
  title: String!
  content: String!
  userId: ID!
}

input CreateUserRequest {
  name: String!
  profileImageId: ID
}

input UpdateUserRequest {
  id: ID!
  name: String!
  profileImageId: ID
}

input CreateImageUploadInput {
  originalFileName: String!
  contentType: String!
}

input CreatePostRequest {
  title: String!
  content: String!
  userId: ID!
}

input UpdatePostRequest {
  id: ID!
  title: String!
  content: String!
}
