spring:
  application:
    name: graphql-sample

  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  graphql:
    graphiql:
      enabled: true

  grpc:
    client:
      default-channel:
        address: static://localhost:9090
